---
galaxy_info:
  role_name: k3s
  author: zepzeper
  description: k3s server or agent installation
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: Debian
      versions:
        - bookworm
        - trixie
  galaxy_tags: [cloud, clustering]

dependencies: []
