---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - calibre
  - forgejo
  - forgejo-runner
  - home-assistant
  - homepage
  - mealie
  - media
  - paperless
  - pihole
  - tuliprox
  - uptimekuma
  - vaultwarden
