---
- name: Full deployment sequence
  ansible.builtin.import_playbook: bootstrap.yml

- name: Deploy Tailscale and K3s
  ansible.builtin.import_playbook: k3s.yml

- name: Deploy Kubernetes manifests
  ansible.builtin.import_playbook: k3s-manifests.yml

- name: Install and configure backup system
  ansible.builtin.import_playbook: backup.yml
